In [2]:
import pandas as pd
df = pd.read_json('nobel_winners.json')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1052 entries, 0 to 1051
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   born_in         1052 non-null   object
 1   category        1052 non-null   object
 2   country         1052 non-null   object
 3   date_of_birth   1044 non-null   object
 4   date_of_death   1044 non-null   object
 5   gender          1040 non-null   object
 6   link            1052 non-null   object
 7   name            1052 non-null   object
 8   place_of_birth  1044 non-null   object
 9   place_of_death  1044 non-null   object
 10  text            1052 non-null   object
 11  year            1052 non-null   int64
dtypes: int64(1), object(11)
memory usage: 98.8+ KB

In [6]:
df.describe(include = 'object')

,born_in,category,country,date_of_birth,date_of_death,gender,link,name,place_of_birth,place_of_death,text
count,1052,1052,1052,1044,1044,1040,1052,1052,1044,1044,1052
unique,40,7,59,853,563,2,893,998,735,410,1043
top,,Physiology or Medicine,United States,7 November 1867,,male,http://en.wikipedia.org/wiki/Michael_Levitt,César Milstein,,,"Ernest Rutherford , born in New Zealand , Che..."
freq,910,250,350,4,362,982,4,2,29,409,2

In [7]:
df.describe(include = 'all')

,born_in,category,country,date_of_birth,date_of_death,gender,link,name,place_of_birth,place_of_death,text,year
count,1052,1052,1052,1044,1044,1040,1052,1052,1044,1044,1052,1052.000000
unique,40,7,59,853,563,2,893,998,735,410,1043,NaN
top,,Physiology or Medicine,United States,7 November 1867,,male,http://en.wikipedia.org/wiki/Michael_Levitt,César Milstein,,,"Ernest Rutherford , born in New Zealand , Che...",NaN
freq,910,250,350,4,362,982,4,2,29,409,2,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1968.729087
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.155829
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1809.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1947.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1975.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1996.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.000000

In [8]:
df.columns

Index(['born_in', 'category', 'country', 'date_of_birth', 'date_of_death',
       'gender', 'link', 'name', 'place_of_birth', 'place_of_death', 'text',
       'year'],
      dtype='object')

In [9]:
df.index

RangeIndex(start=0, stop=1052, step=1)

In [10]:
df

,born_in,category,country,date_of_birth,date_of_death,gender,link,name,place_of_birth,place_of_death,text,year
0,,Physiology or Medicine,Argentina,8 October 1927,24 March 2002,male,http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein,César Milstein,"Bahía Blanca , Argentina","Cambridge , England","César Milstein , Physiology or Medicine, 1984",1984
1,Bosnia and Herzegovina,Literature,,9 October 1892,13 March 1975,male,http://en.wikipedia.org/wiki/Ivo_Andric,Ivo Andric *,"Dolac (village near Travnik), Austria-Hungary ...","Belgrade, SR Serbia, SFR Yugoslavia (present-d...","Ivo Andric *, born in then Austria–Hungary ,...",1961
2,Bosnia and Herzegovina,Chemistry,,"July 23, 1906",1998-01-07,male,http://en.wikipedia.org/wiki/Vladimir_Prelog,Vladimir Prelog *,"Sarajevo , Bosnia and Herzegovina , then part...","Zürich , Switzerland","Vladimir Prelog *, born in then Austria–Hung...",1975
3,,Peace,Belgium,None,None,None,http://en.wikipedia.org/wiki/Institut_de_Droit...,Institut de Droit International,None,None,"Institut de Droit International , Peace, 1904",1904
4,,Peace,Belgium,26 July 1829,6 October 1912,male,http://en.wikipedia.org/wiki/Auguste_Marie_Fra...,Auguste Beernaert,"Ostend , Netherlands (now Belgium )","Lucerne , Switzerland","Auguste Beernaert , Peace, 1909",1909
...,...,...,...,...,...,...,...,...,...,...,...,...
1047,,Physics,Australia,"February 24, 1967",,male,http://en.wikipedia.org/wiki/Brian_P._Schmidt,Brian P. Schmidt,"Missoula, Montana",,"Brian P. Schmidt , born in the United States ...",2011
1048,,Peace,Argentina,"November 1, 1878","May 5, 1959",male,http://en.wikipedia.org/wiki/Carlos_Saavedra_L...,Carlos Saavedra Lamas,"Buenos Aires , Argentina","Buenos Aires, Argentina","Carlos Saavedra Lamas , Peace, 1936",1936
1049,,Physiology or Medicine,Argentina,1887-04-10,1971-09-21,male,http://en.wikipedia.org/wiki/Bernardo_Houssay,Bernardo Houssay,"Buenos Aires , Argentina","Buenos Aires , Argentina","Bernardo Houssay , Physiology or Medicine, 1947",1947
1050,,Chemistry,Argentina,1906-9-6,1987-12-2,male,http://en.wikipedia.org/wiki/Luis_Federico_Leloir,Luis Federico Leloir,"Paris , France","Buenos Aires , Argentina","Luis Federico Leloir , Chemistry, 1970",1970
1051,,Peace,Argentina,"November 26, 1931",,male,http://en.wikipedia.org/wiki/Adolfo_P%C3%A9rez...,Adolfo Pérez Esquivel,Buenos Aires,,"Adolfo Pérez Esquivel , Peace, 1980",1980

In [17]:
df.set_index('name')
#df.set_index('name', inplace = 'True') 儲存異動
df = df.set_index('name') #儲存異動
df

,born_in,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
name,,,,,,,,,,,
César Milstein,,Physiology or Medicine,Argentina,8 October 1927,24 March 2002,male,http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein,"Bahía Blanca , Argentina","Cambridge , England","César Milstein , Physiology or Medicine, 1984",1984
Ivo Andric *,Bosnia and Herzegovina,Literature,,9 October 1892,13 March 1975,male,http://en.wikipedia.org/wiki/Ivo_Andric,"Dolac (village near Travnik), Austria-Hungary ...","Belgrade, SR Serbia, SFR Yugoslavia (present-d...","Ivo Andric *, born in then Austria–Hungary ,...",1961
Vladimir Prelog *,Bosnia and Herzegovina,Chemistry,,"July 23, 1906",1998-01-07,male,http://en.wikipedia.org/wiki/Vladimir_Prelog,"Sarajevo , Bosnia and Herzegovina , then part...","Zürich , Switzerland","Vladimir Prelog *, born in then Austria–Hung...",1975
Institut de Droit International,,Peace,Belgium,None,None,None,http://en.wikipedia.org/wiki/Institut_de_Droit...,None,None,"Institut de Droit International , Peace, 1904",1904
Auguste Beernaert,,Peace,Belgium,26 July 1829,6 October 1912,male,http://en.wikipedia.org/wiki/Auguste_Marie_Fra...,"Ostend , Netherlands (now Belgium )","Lucerne , Switzerland","Auguste Beernaert , Peace, 1909",1909
...,...,...,...,...,...,...,...,...,...,...,...
Brian P. Schmidt,,Physics,Australia,"February 24, 1967",,male,http://en.wikipedia.org/wiki/Brian_P._Schmidt,"Missoula, Montana",,"Brian P. Schmidt , born in the United States ...",2011
Carlos Saavedra Lamas,,Peace,Argentina,"November 1, 1878","May 5, 1959",male,http://en.wikipedia.org/wiki/Carlos_Saavedra_L...,"Buenos Aires , Argentina","Buenos Aires, Argentina","Carlos Saavedra Lamas , Peace, 1936",1936
Bernardo Houssay,,Physiology or Medicine,Argentina,1887-04-10,1971-09-21,male,http://en.wikipedia.org/wiki/Bernardo_Houssay,"Buenos Aires , Argentina","Buenos Aires , Argentina","Bernardo Houssay , Physiology or Medicine, 1947",1947
Luis Federico Leloir,,Chemistry,Argentina,1906-9-6,1987-12-2,male,http://en.wikipedia.org/wiki/Luis_Federico_Leloir,"Paris , France","Buenos Aires , Argentina","Luis Federico Leloir , Chemistry, 1970",1970
Adolfo Pérez Esquivel,,Peace,Argentina,"November 26, 1931",,male,http://en.wikipedia.org/wiki/Adolfo_P%C3%A9rez...,Buenos Aires,,"Adolfo Pérez Esquivel , Peace, 1980",1980

In [19]:
df.loc[['César Milstein', 'Auguste Beernaert'], ['category', 'country']]
#select 'category', 'country' from nobels where name in ('César Milstein', 'Auguste Beernaert')

                                 category         country
name
César Milstein     Physiology or Medicine       Argentina
César Milstein     Physiology or Medicine  United Kingdom
Auguste Beernaert                   Peace         Belgium

In [22]:
df.iloc[[0, 4],[1, 2]]

                                 category    country
name
César Milstein     Physiology or Medicine  Argentina
Auguste Beernaert                   Peace    Belgium

In [33]:
df = df.reset_index()
df

,name,born_in,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
0,César Milstein,,Physiology or Medicine,Argentina,8 October 1927,24 March 2002,male,http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein,"Bahía Blanca , Argentina","Cambridge , England","César Milstein , Physiology or Medicine, 1984",1984
1,Ivo Andric *,Bosnia and Herzegovina,Literature,,9 October 1892,13 March 1975,male,http://en.wikipedia.org/wiki/Ivo_Andric,"Dolac (village near Travnik), Austria-Hungary ...","Belgrade, SR Serbia, SFR Yugoslavia (present-d...","Ivo Andric *, born in then Austria–Hungary ,...",1961
2,Vladimir Prelog *,Bosnia and Herzegovina,Chemistry,,"July 23, 1906",1998-01-07,male,http://en.wikipedia.org/wiki/Vladimir_Prelog,"Sarajevo , Bosnia and Herzegovina , then part...","Zürich , Switzerland","Vladimir Prelog *, born in then Austria–Hung...",1975
3,Institut de Droit International,,Peace,Belgium,None,None,None,http://en.wikipedia.org/wiki/Institut_de_Droit...,None,None,"Institut de Droit International , Peace, 1904",1904
4,Auguste Beernaert,,Peace,Belgium,26 July 1829,6 October 1912,male,http://en.wikipedia.org/wiki/Auguste_Marie_Fra...,"Ostend , Netherlands (now Belgium )","Lucerne , Switzerland","Auguste Beernaert , Peace, 1909",1909
...,...,...,...,...,...,...,...,...,...,...,...,...
1047,Brian P. Schmidt,,Physics,Australia,"February 24, 1967",,male,http://en.wikipedia.org/wiki/Brian_P._Schmidt,"Missoula, Montana",,"Brian P. Schmidt , born in the United States ...",2011
1048,Carlos Saavedra Lamas,,Peace,Argentina,"November 1, 1878","May 5, 1959",male,http://en.wikipedia.org/wiki/Carlos_Saavedra_L...,"Buenos Aires , Argentina","Buenos Aires, Argentina","Carlos Saavedra Lamas , Peace, 1936",1936
1049,Bernardo Houssay,,Physiology or Medicine,Argentina,1887-04-10,1971-09-21,male,http://en.wikipedia.org/wiki/Bernardo_Houssay,"Buenos Aires , Argentina","Buenos Aires , Argentina","Bernardo Houssay , Physiology or Medicine, 1947",1947
1050,Luis Federico Leloir,,Chemistry,Argentina,1906-9-6,1987-12-2,male,http://en.wikipedia.org/wiki/Luis_Federico_Leloir,"Paris , France","Buenos Aires , Argentina","Luis Federico Leloir , Chemistry, 1970",1970
1051,Adolfo Pérez Esquivel,,Peace,Argentina,"November 26, 1931",,male,http://en.wikipedia.org/wiki/Adolfo_P%C3%A9rez...,Buenos Aires,,"Adolfo Pérez Esquivel , Peace, 1980",1980

In [34]:
df['year']

0       1984
1       1961
2       1975
3       1904
4       1909
        ...
1047    2011
1048    1936
1049    1947
1050    1970
1051    1980
Name: year, Length: 1052, dtype: int64

In [38]:
df.year

0       1984
1       1961
2       1975
3       1904
4       1909
        ...
1047    2011
1048    1936
1049    1947
1050    1970
1051    1980
Name: year, Length: 1052, dtype: int64

In [40]:
df.loc[:, 'year']

0       1984
1       1961
2       1975
3       1904
4       1909
        ...
1047    2011
1048    1936
1049    1947
1050    1970
1051    1980
Name: year, Length: 1052, dtype: int64

In [44]:
df[['name', 'category', 'year']]

                                 name                category  year
0                      César Milstein  Physiology or Medicine  1984
1                        Ivo Andric *              Literature  1961
2                   Vladimir Prelog *               Chemistry  1975
3     Institut de Droit International                   Peace  1904
4                   Auguste Beernaert                   Peace  1909
...                               ...                     ...   ...
1047                 Brian P. Schmidt                 Physics  2011
1048            Carlos Saavedra Lamas                   Peace  1936
1049                 Bernardo Houssay  Physiology or Medicine  1947
1050             Luis Federico Leloir               Chemistry  1970
1051            Adolfo Pérez Esquivel                   Peace  1980

[1052 rows x 3 columns]

In [57]:
mask = df['year'] > 2000
df[mask].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 202 entries, 13 to 1047
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            202 non-null    object
 1   born_in         202 non-null    object
 2   category        202 non-null    object
 3   country         202 non-null    object
 4   date_of_birth   201 non-null    object
 5   date_of_death   201 non-null    object
 6   gender          200 non-null    object
 7   link            202 non-null    object
 8   place_of_birth  201 non-null    object
 9   place_of_death  201 non-null    object
 10  text            202 non-null    object
 11  year            202 non-null    int64
dtypes: int64(1), object(11)
memory usage: 20.5+ KB

In [53]:
df[mask][['name', 'category', 'year']].describe(include = 'object')

                  name category
count              202      202
unique             185        6
top     Leonid Hurwicz  Physics
freq                 2       48

In [58]:
df['born_in'][df['born_in'] == '']

0
3
4
5
6
       ..
1047
1048
1049
1050
1051
Name: born_in, Length: 910, dtype: object

In [60]:
df_born_in = df[df['born_in'] != '']
df_born_in

,name,born_in,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
1,Ivo Andric *,Bosnia and Herzegovina,Literature,,9 October 1892,13 March 1975,male,http://en.wikipedia.org/wiki/Ivo_Andric,"Dolac (village near Travnik), Austria-Hungary ...","Belgrade, SR Serbia, SFR Yugoslavia (present-d...","Ivo Andric *, born in then Austria–Hungary ,...",1961
2,Vladimir Prelog *,Bosnia and Herzegovina,Chemistry,,"July 23, 1906",1998-01-07,male,http://en.wikipedia.org/wiki/Vladimir_Prelog,"Sarajevo , Bosnia and Herzegovina , then part...","Zürich , Switzerland","Vladimir Prelog *, born in then Austria–Hung...",1975
14,Simon Kuznets *,Belarus,Economics,,"April 30, 1901","July 8, 1985",male,http://en.wikipedia.org/wiki/Simon_Kuznets,Pinsk,"Cambridge, Massachusetts","Simon Kuznets *, born in then Russian Empire,...",1971
15,Menachem Begin *,Belarus,Peace,,16 August 1913,9 March 1992,male,http://en.wikipedia.org/wiki/Menachem_Begin,"Brest , Russian Empire","Tel Aviv , Israel","Menachem Begin *, born in then Russian Empire...",1978
16,Shimon Peres *,Belarus,Peace,,2 August 1923,,male,http://en.wikipedia.org/wiki/Shimon_Peres,Poland,,"Shimon Peres *, born in then Poland, now Bela...",1994
...,...,...,...,...,...,...,...,...,...,...,...,...
1034,Martin Karplus *,Austria,Chemistry,,"March 15, 1930",,male,http://en.wikipedia.org/wiki/Martin_Karplus,"Vienna , Austria",,"Martin Karplus *, Chemistry, 2013",2013
1035,William Lawrence Bragg *,Australia,Physics,,31 March 1890,1 July 1971,male,http://en.wikipedia.org/wiki/William_Lawrence_...,"North Adelaide , South Australia","Waldringfield , Suffolk, England","William Lawrence Bragg *, Physics, 1915",1915
1039,Aleksandr M. Prokhorov *,Australia,Physics,,11 July 1916,8 January 2002,male,http://en.wikipedia.org/wiki/Aleksandr_M._Prok...,"Atherton, Queensland , Australia","Moscow , Russia","Aleksandr M. Prokhorov *, Physics, 1964",1964
1041,John Warcup Cornforth *,Australia,Chemistry,,7 September 1917,8 December 2013,male,http://en.wikipedia.org/wiki/John_Warcup_Cornf...,"Sydney , Australia",England,"John Warcup Cornforth *, Chemistry, 1975",1975
1046,Elizabeth H. Blackburn *,Australia,Physiology or Medicine,,1948-11-26,,female,http://en.wikipedia.org/wiki/Elizabeth_H._Blac...,"Hobart , Tasmania , Australia",,"Elizabeth H. Blackburn *, Physiology or Medici...",2009

In [62]:
import numpy as np
df['born_in'] = df['born_in'].replace('', np.nan)
df['born_in']

0                          NaN
1       Bosnia and Herzegovina
2       Bosnia and Herzegovina
3                          NaN
4                          NaN
                 ...
1047                       NaN
1048                       NaN
1049                       NaN
1050                       NaN
1051                       NaN
Name: born_in, Length: 1052, dtype: object

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1052 entries, 0 to 1051
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            1052 non-null   object
 1   born_in         142 non-null    object
 2   category        1052 non-null   object
 3   country         1052 non-null   object
 4   date_of_birth   1044 non-null   object
 5   date_of_death   1044 non-null   object
 6   gender          1040 non-null   object
 7   link            1052 non-null   object
 8   place_of_birth  1044 non-null   object
 9   place_of_death  1044 non-null   object
 10  text            1052 non-null   object
 11  year            1052 non-null   int64
dtypes: int64(1), object(11)
memory usage: 98.8+ KB

In [64]:
df = df.drop('born_in', axis = 1)
df

,name,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
0,César Milstein,Physiology or Medicine,Argentina,8 October 1927,24 March 2002,male,http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein,"Bahía Blanca , Argentina","Cambridge , England","César Milstein , Physiology or Medicine, 1984",1984
1,Ivo Andric *,Literature,,9 October 1892,13 March 1975,male,http://en.wikipedia.org/wiki/Ivo_Andric,"Dolac (village near Travnik), Austria-Hungary ...","Belgrade, SR Serbia, SFR Yugoslavia (present-d...","Ivo Andric *, born in then Austria–Hungary ,...",1961
2,Vladimir Prelog *,Chemistry,,"July 23, 1906",1998-01-07,male,http://en.wikipedia.org/wiki/Vladimir_Prelog,"Sarajevo , Bosnia and Herzegovina , then part...","Zürich , Switzerland","Vladimir Prelog *, born in then Austria–Hung...",1975
3,Institut de Droit International,Peace,Belgium,None,None,None,http://en.wikipedia.org/wiki/Institut_de_Droit...,None,None,"Institut de Droit International , Peace, 1904",1904
4,Auguste Beernaert,Peace,Belgium,26 July 1829,6 October 1912,male,http://en.wikipedia.org/wiki/Auguste_Marie_Fra...,"Ostend , Netherlands (now Belgium )","Lucerne , Switzerland","Auguste Beernaert , Peace, 1909",1909
...,...,...,...,...,...,...,...,...,...,...,...
1047,Brian P. Schmidt,Physics,Australia,"February 24, 1967",,male,http://en.wikipedia.org/wiki/Brian_P._Schmidt,"Missoula, Montana",,"Brian P. Schmidt , born in the United States ...",2011
1048,Carlos Saavedra Lamas,Peace,Argentina,"November 1, 1878","May 5, 1959",male,http://en.wikipedia.org/wiki/Carlos_Saavedra_L...,"Buenos Aires , Argentina","Buenos Aires, Argentina","Carlos Saavedra Lamas , Peace, 1936",1936
1049,Bernardo Houssay,Physiology or Medicine,Argentina,1887-04-10,1971-09-21,male,http://en.wikipedia.org/wiki/Bernardo_Houssay,"Buenos Aires , Argentina","Buenos Aires , Argentina","Bernardo Houssay , Physiology or Medicine, 1947",1947
1050,Luis Federico Leloir,Chemistry,Argentina,1906-9-6,1987-12-2,male,http://en.wikipedia.org/wiki/Luis_Federico_Leloir,"Paris , France","Buenos Aires , Argentina","Luis Federico Leloir , Chemistry, 1970",1970
1051,Adolfo Pérez Esquivel,Peace,Argentina,"November 26, 1931",,male,http://en.wikipedia.org/wiki/Adolfo_P%C3%A9rez...,Buenos Aires,,"Adolfo Pérez Esquivel , Peace, 1980",1980

In [66]:
df = df.replace('', np.nan)
df

,name,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
0,César Milstein,Physiology or Medicine,Argentina,8 October 1927,24 March 2002,male,http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein,"Bahía Blanca , Argentina","Cambridge , England","César Milstein , Physiology or Medicine, 1984",1984
1,Ivo Andric *,Literature,NaN,9 October 1892,13 March 1975,male,http://en.wikipedia.org/wiki/Ivo_Andric,"Dolac (village near Travnik), Austria-Hungary ...","Belgrade, SR Serbia, SFR Yugoslavia (present-d...","Ivo Andric *, born in then Austria–Hungary ,...",1961
2,Vladimir Prelog *,Chemistry,NaN,"July 23, 1906",1998-01-07,male,http://en.wikipedia.org/wiki/Vladimir_Prelog,"Sarajevo , Bosnia and Herzegovina , then part...","Zürich , Switzerland","Vladimir Prelog *, born in then Austria–Hung...",1975
3,Institut de Droit International,Peace,Belgium,None,None,None,http://en.wikipedia.org/wiki/Institut_de_Droit...,None,None,"Institut de Droit International , Peace, 1904",1904
4,Auguste Beernaert,Peace,Belgium,26 July 1829,6 October 1912,male,http://en.wikipedia.org/wiki/Auguste_Marie_Fra...,"Ostend , Netherlands (now Belgium )","Lucerne , Switzerland","Auguste Beernaert , Peace, 1909",1909
...,...,...,...,...,...,...,...,...,...,...,...
1047,Brian P. Schmidt,Physics,Australia,"February 24, 1967",NaN,male,http://en.wikipedia.org/wiki/Brian_P._Schmidt,"Missoula, Montana",NaN,"Brian P. Schmidt , born in the United States ...",2011
1048,Carlos Saavedra Lamas,Peace,Argentina,"November 1, 1878","May 5, 1959",male,http://en.wikipedia.org/wiki/Carlos_Saavedra_L...,"Buenos Aires , Argentina","Buenos Aires, Argentina","Carlos Saavedra Lamas , Peace, 1936",1936
1049,Bernardo Houssay,Physiology or Medicine,Argentina,1887-04-10,1971-09-21,male,http://en.wikipedia.org/wiki/Bernardo_Houssay,"Buenos Aires , Argentina","Buenos Aires , Argentina","Bernardo Houssay , Physiology or Medicine, 1947",1947
1050,Luis Federico Leloir,Chemistry,Argentina,1906-9-6,1987-12-2,male,http://en.wikipedia.org/wiki/Luis_Federico_Leloir,"Paris , France","Buenos Aires , Argentina","Luis Federico Leloir , Chemistry, 1970",1970
1051,Adolfo Pérez Esquivel,Peace,Argentina,"November 26, 1931",NaN,male,http://en.wikipedia.org/wiki/Adolfo_P%C3%A9rez...,Buenos Aires,NaN,"Adolfo Pérez Esquivel , Peace, 1980",1980

In [87]:
df[df['name'].str.contains('\*')]

Empty DataFrame
Columns: [name, category, country, date_of_birth, date_of_death, gender, link, place_of_birth, place_of_death, text, year]
Index: []

In [85]:
df['name'] = df['name'].str.replace('*', '')
df['name'] = df['name'].str.strip()
df['name']

# #df['born_in'].replace('',np.nan)  #整個欄位符合條件就完整取代
# df['name'] = df['name'].str.replace('*','')    #部分文字符合條件就取代部分文字
# df['name'] = df['name'].str.strip()
# df['name']

C:\Users\User\AppData\Local\Temp\ipykernel_13276\336876187.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['name'] = df['name'].str.replace('*', '')

0                        César Milstein
1                            Ivo Andric
2                       Vladimir Prelog
3       Institut de Droit International
4                     Auguste Beernaert
                     ...
1047                   Brian P. Schmidt
1048              Carlos Saavedra Lamas
1049                   Bernardo Houssay
1050               Luis Federico Leloir
1051              Adolfo Pérez Esquivel
Name: name, Length: 1052, dtype: object

In [90]:
df[df.duplicated(['name', 'category'])]

,name,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
90,Menachem Begin,Peace,Israel,16 August 1913,9 March 1992,male,http://en.wikipedia.org/wiki/Menachem_Begin,"Brest , Russian Empire","Tel Aviv , Israel","Menachem Begin , born in what was then Russia...",1978
91,Shimon Peres,Peace,Israel,2 August 1923,NaN,male,http://en.wikipedia.org/wiki/Shimon_Peres,Poland,NaN,"Shimon Peres , born in what was then Poland, ...",1994
109,Wilhelm Ostwald,Chemistry,NaN,1853-09-02,1932-04-04,male,http://en.wikipedia.org/wiki/Wilhelm_Ostwald,"Riga , Latvia","Leipzig , Germany","Wilhelm Ostwald *, born in then Russian Empir...",1909
121,Aaron Klug,Chemistry,South Africa,11 August 1926,NaN,male,http://en.wikipedia.org/wiki/Aaron_Klug,"Želva, Lithuania",NaN,"Aaron Klug , Chemistry, 1982",1982
131,Aaron Klug,Chemistry,United Kingdom,11 August 1926,NaN,male,http://en.wikipedia.org/wiki/Aaron_Klug,"Želva, Lithuania",NaN,"Aaron Klug , born in Lithuania , Chemistry, 1982",1982
...,...,...,...,...,...,...,...,...,...,...,...
1039,Aleksandr M. Prokhorov,Physics,NaN,11 July 1916,8 January 2002,male,http://en.wikipedia.org/wiki/Aleksandr_M._Prok...,"Atherton, Queensland , Australia","Moscow , Russia","Aleksandr M. Prokhorov *, Physics, 1964",1964
1040,Patrick White,Literature,Australia,28 May 1912,30 September 1990,male,http://en.wikipedia.org/wiki/Patrick_White,"Knightsbridge , London","Sydney, Australia","Patrick White , born in the United Kingdom , ...",1973
1042,John Harsanyi,Economics,Australia,"May 29, 1920","August 9, 2000",male,http://en.wikipedia.org/wiki/John_Harsanyi,"Budapest , Hungary","Berkeley, California , USA","John Harsanyi , Economics, 1994",1994
1047,Brian P. Schmidt,Physics,Australia,"February 24, 1967",NaN,male,http://en.wikipedia.org/wiki/Brian_P._Schmidt,"Missoula, Montana",NaN,"Brian P. Schmidt , born in the United States ...",2011
1050,Luis Federico Leloir,Chemistry,Argentina,1906-9-6,1987-12-2,male,http://en.wikipedia.org/wiki/Luis_Federico_Leloir,"Paris , France","Buenos Aires , Argentina","Luis Federico Leloir , Chemistry, 1970",1970

In [99]:
sorted(list(df[df.duplicated('name')]['name']))

['Aaron Klug',
 'Aaron Klug',
 'Alan MacDiarmid',
 'Albert Einstein',
 'Albert Schweitzer',
 'Aleksandr M. Prokhorov',
 'Alexei A. Abrikosov',
 'Alfred Werner',
 'Allan M. Cormack',
 'Andre Geim',
 'Andrew Schally',
 'Anthony J. Leggett',
 'Arieh Warshel',
 'Arno Penzias',
 'Avram Hershko',
 'Baruj Benacerraf',
 'Bernard Katz',
 'Bertha von Suttner',
 'Betty Williams',
 'Brian P. Schmidt',
 'Carlos Filipe Ximenes Belo',
 'Charles B. Huggins',
 'Charles K. Kao',
 'Charles K. Kao',
 'Chen Ning Yang',
 'Christian de Duve',
 'Czesław Miłosz',
 'Czesław Miłosz',
 'César Milstein',
 'Daniel Bovet',
 'Daniel C. Tsui',
 'Daniel Kahneman',
 'David H. Hubel',
 'David Trimble',
 'Edmond H. Fischer',
 'Ei-ichi Negishi',
 'Elias Canetti',
 'Elie Wiesel',
 'Eric R. Kandel',
 'Ernest Rutherford',
 'Ernest Rutherford',
 'Ernst Boris Chain',
 'Eugene Wigner',
 'Felix Bloch',
 'Franco Modigliani',
 'Frederick Sanger',
 'Friderik Pregl',
 'Friedrich Hayek',
 'Gabriel Lippmann',
 'Gao Xingjian',
 'George E. Palade',
 'Georges Charpak',
 'Georges Charpak',
 'Gerhard Herzberg',
 'Gerty Cori',
 'Gérard Debreu',
 'Günter Blobel',
 'Hans Adolf Krebs',
 'Hans G. Dehmelt',
 'Hans von Euler-Chelpin',
 'Henry Dunant',
 'Henry Kissinger',
 'Henry Taube',
 'Herta Müller',
 'Ilya Ilyich Mechnikov',
 'Ilya Prigogine',
 'Isaac Bashevis Singer',
 'Ivan Bunin',
 'Ivar Giaever',
 'Ivo Andrić',
 'Jack Steinberger',
 'Jack W. Szostak',
 'John Bardeen',
 'John Harsanyi',
 "John O'Keefe",
 'Joseph Rotblat',
 'José Ramos-Horta',
 'Jules A. Hoffmann',
 'Konrad Bloch',
 'Konstantin Novoselov',
 'Lars Onsager',
 'Leonid Hurwicz',
 'Leonid Hurwicz',
 'Leopold Ružička',
 'Linus C. Pauling',
 'Luis Federico Leloir',
 'Maria Goeppert-Mayer',
 'Marie Curie',
 'Marie Skłodowska-Curie',
 'Martin Karplus',
 'Maurice Wilkins',
 'Max Born',
 'Max Delbrück',
 'Menachem Begin',
 'Menachem Begin',
 'Michael Levitt',
 'Michael Levitt',
 'Michael Levitt',
 'Michael Smith',
 'Mother Teresa',
 'Myron Scholes',
 'Médecins Sans Frontières',
 'Nelly Sachs',
 'Nicolaas Bloembergen',
 'Niels Kaj Jerne',
 'Niels Ryberg Finsen',
 'Oliver Smithies',
 'Osamu Shimomura',
 'Otto Stern',
 'Patrick White',
 'Peter Medawar',
 'Philipp Lenard',
 'Ragnar Granit',
 'Ralph M. Steinman',
 'Renato Dulbecco',
 'Riccardo Giacconi',
 'Richard Adolf Zsigmondy',
 'Richard Kuhn',
 'Rita Levi-Montalcini',
 'Roald Hoffmann',
 'Roald Hoffmann',
 'Robert Aumann',
 'Robert Bárány',
 'Roger Guillemin',
 'Ronald Coase',
 'Rudolph A. Marcus',
 'Salvador Luria',
 'Saul Bellow',
 'Selman A. Waksman',
 'Severo Ochoa',
 'Seán MacBride',
 'Shimon Peres',
 'Shimon Peres',
 'Shmuel Yosef Agnon',
 'Shuji Nakamura',
 'Sidney Altman',
 'Simon Kuznets',
 'Stefan Hell',
 'Subrahmanyan Chandrasekhar',
 'Sydney Brenner',
 'Sydney Brenner',
 'Tadeus Reichstein',
 'Thomas C. Südhof',
 'Tsung-Dao Lee',
 'Venkatraman Ramakrishnan',
 'Vladimir Prelog',
 'Walter Kohn',
 'Wassily Leontief',
 'Wilhelm Ostwald',
 'Wilhelm Ostwald',
 'Willard S. Boyle',
 'William Giauque',
 'William Lawrence Bragg',
 'William Vickrey',
 'Yoichiro Nambu',
 'Zhores Ivanovich Alferov']

In [106]:
df[df.duplicated('name')].count()

name              156
category          155
country            83
date_of_birth     155
date_of_death      95
gender            152
link              156
place_of_birth    153
place_of_death     90
text              156
year              156
dtype: int64

In [104]:
df[df.duplicated('name')].sort_values(['name'], ascending = [1])

,name,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
121,Aaron Klug,Chemistry,South Africa,11 August 1926,NaN,male,http://en.wikipedia.org/wiki/Aaron_Klug,"Želva, Lithuania",NaN,"Aaron Klug , Chemistry, 1982",1982
131,Aaron Klug,Chemistry,United Kingdom,11 August 1926,NaN,male,http://en.wikipedia.org/wiki/Aaron_Klug,"Želva, Lithuania",NaN,"Aaron Klug , born in Lithuania , Chemistry, 1982",1982
742,Alan MacDiarmid,Chemistry,NaN,14 April 1927,7 February 2007,male,http://en.wikipedia.org/wiki/Alan_MacDiarmid,"Masterton , New Zealand","Philadelphia , U.S.","Alan MacDiarmid *, Chemistry, 2000",2000
844,Albert Einstein,Physics,Germany,1879-03-14,1955-04-18,male,http://en.wikipedia.org/wiki/Albert_Einstein,"Ulm , Baden-Württemberg , German Empire","Princeton, New Jersey , U.S.","Albert Einstein , Physics, 1921",1921
870,Albert Schweitzer,Peace,NaN,14 January 1875,4 September 1965,male,http://en.wikipedia.org/wiki/Albert_Schweitzer,"Kaysersberg , Elsass-Lothringen , Germany (no...","Lambaréné , Gabon","Albert Schweitzer *, Peace, 1952",1952
...,...,...,...,...,...,...,...,...,...,...,...
987,William Giauque,Chemistry,NaN,"May 12, 1895","March 28, 1982",male,http://en.wikipedia.org/wiki/William_Giauque,"Niagara Falls, Ontario , Canada","Berkeley , California","William Giauque *, Chemistry, 1949",1949
1035,William Lawrence Bragg,Physics,NaN,31 March 1890,1 July 1971,male,http://en.wikipedia.org/wiki/William_Lawrence_...,"North Adelaide , South Australia","Waldringfield , Suffolk, England","William Lawrence Bragg *, Physics, 1915",1915
1001,William Vickrey,Economics,NaN,21 June 1914,11 October 1996,male,http://en.wikipedia.org/wiki/William_Vickrey,"Victoria, British Columbia , Canada","Harrison, New York , USA","William Vickrey *, Economics, 1996",1996
773,Yoichiro Nambu,Physics,Japan,"January 18, 1921",NaN,male,http://en.wikipedia.org/wiki/Yoichiro_Nambu,"Tokyo, Japan",NaN,"Yoichiro Nambu , Physics, 2008",2008
1010,Zhores Ivanovich Alferov,Physics,NaN,1930-03-15,NaN,male,http://en.wikipedia.org/wiki/Zhores_Ivanovich_...,"Vitebsk , BSSR , Soviet Union",NaN,"Zhores Ivanovich Alferov *, born in then Sovi...",2000

In [111]:
dups_name = df[df.duplicated('name')]['name']
df[df['name'].isin(dups_name)].sort_values(['name'], ascending = [1])

,name,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
131,Aaron Klug,Chemistry,United Kingdom,11 August 1926,NaN,male,http://en.wikipedia.org/wiki/Aaron_Klug,"Želva, Lithuania",NaN,"Aaron Klug , born in Lithuania , Chemistry, 1982",1982
121,Aaron Klug,Chemistry,South Africa,11 August 1926,NaN,male,http://en.wikipedia.org/wiki/Aaron_Klug,"Želva, Lithuania",NaN,"Aaron Klug , Chemistry, 1982",1982
106,Aaron Klug,Chemistry,NaN,11 August 1926,NaN,male,http://en.wikipedia.org/wiki/Aaron_Klug,"Želva, Lithuania",NaN,"Aaron Klug *, Chemistry, 1982",1982
440,Alan MacDiarmid,Chemistry,United States,14 April 1927,7 February 2007,male,http://en.wikipedia.org/wiki/Alan_MacDiarmid,"Masterton , New Zealand","Philadelphia , U.S.","Alan MacDiarmid , born in New Zealand , Chemi...",2000
742,Alan MacDiarmid,Chemistry,NaN,14 April 1927,7 February 2007,male,http://en.wikipedia.org/wiki/Alan_MacDiarmid,"Masterton , New Zealand","Philadelphia , U.S.","Alan MacDiarmid *, Chemistry, 2000",2000
...,...,...,...,...,...,...,...,...,...,...,...
417,William Vickrey,Economics,United States,21 June 1914,11 October 1996,male,http://en.wikipedia.org/wiki/William_Vickrey,"Victoria, British Columbia , Canada","Harrison, New York , USA","William Vickrey , born in Canada , Economics,...",1996
489,Yoichiro Nambu,Physics,United States,"January 18, 1921",NaN,male,http://en.wikipedia.org/wiki/Yoichiro_Nambu,"Tokyo, Japan",NaN,"Yoichiro Nambu , born in Japan , Physics, 2008",2008
773,Yoichiro Nambu,Physics,Japan,"January 18, 1921",NaN,male,http://en.wikipedia.org/wiki/Yoichiro_Nambu,"Tokyo, Japan",NaN,"Yoichiro Nambu , Physics, 2008",2008
1010,Zhores Ivanovich Alferov,Physics,NaN,1930-03-15,NaN,male,http://en.wikipedia.org/wiki/Zhores_Ivanovich_...,"Vitebsk , BSSR , Soviet Union",NaN,"Zhores Ivanovich Alferov *, born in then Sovi...",2000
692,Zhores Ivanovich Alferov,Physics,Russia,1930-03-15,NaN,male,http://en.wikipedia.org/wiki/Zhores_Ivanovich_...,"Vitebsk , BSSR , Soviet Union",NaN,"Zhores Ivanovich Alferov , born in then Sovie...",2000

In [113]:
df['name']

0                        César Milstein
1                            Ivo Andric
2                       Vladimir Prelog
3       Institut de Droit International
4                     Auguste Beernaert
                     ...
1047                   Brian P. Schmidt
1048              Carlos Saavedra Lamas
1049                   Bernardo Houssay
1050               Luis Federico Leloir
1051              Adolfo Pérez Esquivel
Name: name, Length: 1052, dtype: object

In [110]:
df[df.duplicated('name')]['name']

90              Menachem Begin
91                Shimon Peres
109            Wilhelm Ostwald
121                 Aaron Klug
131                 Aaron Klug
                 ...
1039    Aleksandr M. Prokhorov
1040             Patrick White
1042             John Harsanyi
1047          Brian P. Schmidt
1050      Luis Federico Leloir
Name: name, Length: 156, dtype: object

In [114]:
sorted(list(df[df['name'].isin(df[df.duplicated('name')]['name'])]['name']))

['Aaron Klug',
 'Aaron Klug',
 'Aaron Klug',
 'Alan MacDiarmid',
 'Alan MacDiarmid',
 'Albert Einstein',
 'Albert Einstein',
 'Albert Schweitzer',
 'Albert Schweitzer',
 'Aleksandr M. Prokhorov',
 'Aleksandr M. Prokhorov',
 'Alexei A. Abrikosov',
 'Alexei A. Abrikosov',
 'Alfred Werner',
 'Alfred Werner',
 'Allan M. Cormack',
 'Allan M. Cormack',
 'Andre Geim',
 'Andre Geim',
 'Andrew Schally',
 'Andrew Schally',
 'Anthony J. Leggett',
 'Anthony J. Leggett',
 'Arieh Warshel',
 'Arieh Warshel',
 'Arno Penzias',
 'Arno Penzias',
 'Avram Hershko',
 'Avram Hershko',
 'Baruj Benacerraf',
 'Baruj Benacerraf',
 'Bernard Katz',
 'Bernard Katz',
 'Bertha von Suttner',
 'Bertha von Suttner',
 'Betty Williams',
 'Betty Williams',
 'Brian P. Schmidt',
 'Brian P. Schmidt',
 'Carlos Filipe Ximenes Belo',
 'Carlos Filipe Ximenes Belo',
 'Charles B. Huggins',
 'Charles B. Huggins',
 'Charles K. Kao',
 'Charles K. Kao',
 'Charles K. Kao',
 'Chen Ning Yang',
 'Chen Ning Yang',
 'Christian de Duve',
 'Christian de Duve',
 'Czesław Miłosz',
 'Czesław Miłosz',
 'Czesław Miłosz',
 'César Milstein',
 'César Milstein',
 'Daniel Bovet',
 'Daniel Bovet',
 'Daniel C. Tsui',
 'Daniel C. Tsui',
 'Daniel Kahneman',
 'Daniel Kahneman',
 'David H. Hubel',
 'David H. Hubel',
 'David Trimble',
 'David Trimble',
 'Edmond H. Fischer',
 'Edmond H. Fischer',
 'Ei-ichi Negishi',
 'Ei-ichi Negishi',
 'Elias Canetti',
 'Elias Canetti',
 'Elie Wiesel',
 'Elie Wiesel',
 'Eric R. Kandel',
 'Eric R. Kandel',
 'Ernest Rutherford',
 'Ernest Rutherford',
 'Ernest Rutherford',
 'Ernst Boris Chain',
 'Ernst Boris Chain',
 'Eugene Wigner',
 'Eugene Wigner',
 'Felix Bloch',
 'Felix Bloch',
 'Franco Modigliani',
 'Franco Modigliani',
 'Frederick Sanger',
 'Frederick Sanger',
 'Friderik Pregl',
 'Friderik Pregl',
 'Friedrich Hayek',
 'Friedrich Hayek',
 'Gabriel Lippmann',
 'Gabriel Lippmann',
 'Gao Xingjian',
 'Gao Xingjian',
 'George E. Palade',
 'George E. Palade',
 'Georges Charpak',
 'Georges Charpak',
 'Georges Charpak',
 'Gerhard Herzberg',
 'Gerhard Herzberg',
 'Gerty Cori',
 'Gerty Cori',
 'Gérard Debreu',
 'Gérard Debreu',
 'Günter Blobel',
 'Günter Blobel',
 'Hans Adolf Krebs',
 'Hans Adolf Krebs',
 'Hans G. Dehmelt',
 'Hans G. Dehmelt',
 'Hans von Euler-Chelpin',
 'Hans von Euler-Chelpin',
 'Henry Dunant',
 'Henry Dunant',
 'Henry Kissinger',
 'Henry Kissinger',
 'Henry Taube',
 'Henry Taube',
 'Herta Müller',
 'Herta Müller',
 'Ilya Ilyich Mechnikov',
 'Ilya Ilyich Mechnikov',
 'Ilya Prigogine',
 'Ilya Prigogine',
 'Isaac Bashevis Singer',
 'Isaac Bashevis Singer',
 'Ivan Bunin',
 'Ivan Bunin',
 'Ivar Giaever',
 'Ivar Giaever',
 'Ivo Andrić',
 'Ivo Andrić',
 'Jack Steinberger',
 'Jack Steinberger',
 'Jack W. Szostak',
 'Jack W. Szostak',
 'John Bardeen',
 'John Bardeen',
 'John Harsanyi',
 'John Harsanyi',
 "John O'Keefe",
 "John O'Keefe",
 'Joseph Rotblat',
 'Joseph Rotblat',
 'José Ramos-Horta',
 'José Ramos-Horta',
 'Jules A. Hoffmann',
 'Jules A. Hoffmann',
 'Konrad Bloch',
 'Konrad Bloch',
 'Konstantin Novoselov',
 'Konstantin Novoselov',
 'Lars Onsager',
 'Lars Onsager',
 'Leonid Hurwicz',
 'Leonid Hurwicz',
 'Leonid Hurwicz',
 'Leopold Ružička',
 'Leopold Ružička',
 'Linus C. Pauling',
 'Linus C. Pauling',
 'Luis Federico Leloir',
 'Luis Federico Leloir',
 'Maria Goeppert-Mayer',
 'Maria Goeppert-Mayer',
 'Marie Curie',
 'Marie Curie',
 'Marie Skłodowska-Curie',
 'Marie Skłodowska-Curie',
 'Martin Karplus',
 'Martin Karplus',
 'Maurice Wilkins',
 'Maurice Wilkins',
 'Max Born',
 'Max Born',
 'Max Delbrück',
 'Max Delbrück',
 'Menachem Begin',
 'Menachem Begin',
 'Menachem Begin',
 'Michael Levitt',
 'Michael Levitt',
 'Michael Levitt',
 'Michael Levitt',
 'Michael Smith',
 'Michael Smith',
 'Mother Teresa',
 'Mother Teresa',
 'Myron Scholes',
 'Myron Scholes',
 'Médecins Sans Frontières',
 'Médecins Sans Frontières',
 'Nelly Sachs',
 'Nelly Sachs',
 'Nicolaas Bloembergen',
 'Nicolaas Bloembergen',
 'Niels Kaj Jerne',
 'Niels Kaj Jerne',
 'Niels Ryberg Finsen',
 'Niels Ryberg Finsen',
 'Oliver Smithies',
 'Oliver Smithies',
 'Osamu Shimomura',
 'Osamu Shimomura',
 'Otto Stern',
 'Otto Stern',
 'Patrick White',
 'Patrick White',
 'Peter Medawar',
 'Peter Medawar',
 'Philipp Lenard',
 'Philipp Lenard',
 'Ragnar Granit',
 'Ragnar Granit',
 'Ralph M. Steinman',
 'Ralph M. Steinman',
 'Renato Dulbecco',
 'Renato Dulbecco',
 'Riccardo Giacconi',
 'Riccardo Giacconi',
 'Richard Adolf Zsigmondy',
 'Richard Adolf Zsigmondy',
 'Richard Kuhn',
 'Richard Kuhn',
 'Rita Levi-Montalcini',
 'Rita Levi-Montalcini',
 'Roald Hoffmann',
 'Roald Hoffmann',
 'Roald Hoffmann',
 'Robert Aumann',
 'Robert Aumann',
 'Robert Bárány',
 'Robert Bárány',
 'Roger Guillemin',
 'Roger Guillemin',
 'Ronald Coase',
 'Ronald Coase',
 'Rudolph A. Marcus',
 'Rudolph A. Marcus',
 'Salvador Luria',
 'Salvador Luria',
 'Saul Bellow',
 'Saul Bellow',
 'Selman A. Waksman',
 'Selman A. Waksman',
 'Severo Ochoa',
 'Severo Ochoa',
 'Seán MacBride',
 'Seán MacBride',
 'Shimon Peres',
 'Shimon Peres',
 'Shimon Peres',
 'Shmuel Yosef Agnon',
 'Shmuel Yosef Agnon',
 'Shuji Nakamura',
 'Shuji Nakamura',
 'Sidney Altman',
 'Sidney Altman',
 'Simon Kuznets',
 'Simon Kuznets',
 'Stefan Hell',
 'Stefan Hell',
 'Subrahmanyan Chandrasekhar',
 'Subrahmanyan Chandrasekhar',
 'Sydney Brenner',
 'Sydney Brenner',
 'Sydney Brenner',
 'Tadeus Reichstein',
 'Tadeus Reichstein',
 'Thomas C. Südhof',
 'Thomas C. Südhof',
 'Tsung-Dao Lee',
 'Tsung-Dao Lee',
 'Venkatraman Ramakrishnan',
 'Venkatraman Ramakrishnan',
 'Vladimir Prelog',
 'Vladimir Prelog',
 'Walter Kohn',
 'Walter Kohn',
 'Wassily Leontief',
 'Wassily Leontief',
 'Wilhelm Ostwald',
 'Wilhelm Ostwald',
 'Wilhelm Ostwald',
 'Willard S. Boyle',
 'Willard S. Boyle',
 'William Giauque',
 'William Giauque',
 'William Lawrence Bragg',
 'William Lawrence Bragg',
 'William Vickrey',
 'William Vickrey',
 'Yoichiro Nambu',
 'Yoichiro Nambu',
 'Zhores Ivanovich Alferov',
 'Zhores Ivanovich Alferov']

In [123]:
df[df['name'].isin(df[df.duplicated('name')]['name'])].sort_values(['name'], ascending = 1) # 只有重複名字的df

,name,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
131,Aaron Klug,Chemistry,United Kingdom,11 August 1926,NaN,male,http://en.wikipedia.org/wiki/Aaron_Klug,"Želva, Lithuania",NaN,"Aaron Klug , born in Lithuania , Chemistry, 1982",1982
121,Aaron Klug,Chemistry,South Africa,11 August 1926,NaN,male,http://en.wikipedia.org/wiki/Aaron_Klug,"Želva, Lithuania",NaN,"Aaron Klug , Chemistry, 1982",1982
106,Aaron Klug,Chemistry,NaN,11 August 1926,NaN,male,http://en.wikipedia.org/wiki/Aaron_Klug,"Želva, Lithuania",NaN,"Aaron Klug *, Chemistry, 1982",1982
440,Alan MacDiarmid,Chemistry,United States,14 April 1927,7 February 2007,male,http://en.wikipedia.org/wiki/Alan_MacDiarmid,"Masterton , New Zealand","Philadelphia , U.S.","Alan MacDiarmid , born in New Zealand , Chemi...",2000
742,Alan MacDiarmid,Chemistry,NaN,14 April 1927,7 February 2007,male,http://en.wikipedia.org/wiki/Alan_MacDiarmid,"Masterton , New Zealand","Philadelphia , U.S.","Alan MacDiarmid *, Chemistry, 2000",2000
...,...,...,...,...,...,...,...,...,...,...,...
417,William Vickrey,Economics,United States,21 June 1914,11 October 1996,male,http://en.wikipedia.org/wiki/William_Vickrey,"Victoria, British Columbia , Canada","Harrison, New York , USA","William Vickrey , born in Canada , Economics,...",1996
489,Yoichiro Nambu,Physics,United States,"January 18, 1921",NaN,male,http://en.wikipedia.org/wiki/Yoichiro_Nambu,"Tokyo, Japan",NaN,"Yoichiro Nambu , born in Japan , Physics, 2008",2008
773,Yoichiro Nambu,Physics,Japan,"January 18, 1921",NaN,male,http://en.wikipedia.org/wiki/Yoichiro_Nambu,"Tokyo, Japan",NaN,"Yoichiro Nambu , Physics, 2008",2008
1010,Zhores Ivanovich Alferov,Physics,NaN,1930-03-15,NaN,male,http://en.wikipedia.org/wiki/Zhores_Ivanovich_...,"Vitebsk , BSSR , Soviet Union",NaN,"Zhores Ivanovich Alferov *, born in then Sovi...",2000
692,Zhores Ivanovich Alferov,Physics,Russia,1930-03-15,NaN,male,http://en.wikipedia.org/wiki/Zhores_Ivanovich_...,"Vitebsk , BSSR , Soviet Union",NaN,"Zhores Ivanovich Alferov , born in then Sovie...",2000

In [132]:
df[df['name'].isin(df[df.duplicated('name')]['name'])].groupby('name')['name'].count()

pandas.core.series.Series

In [135]:
df[df['name'].isin(df[df.duplicated('name')]['name'])].sort_values(['name'], ascending = [1])['name', ]

131                   Aaron Klug
121                   Aaron Klug
106                   Aaron Klug
440              Alan MacDiarmid
742              Alan MacDiarmid
                  ...
417              William Vickrey
489               Yoichiro Nambu
773               Yoichiro Nambu
1010    Zhores Ivanovich Alferov
692     Zhores Ivanovich Alferov
Name: name, Length: 299, dtype: object

In [148]:
df[df.duplicated(['name', 'category', 'year'])][['name', 'category', 'year']]

                        name    category  year
90            Menachem Begin       Peace  1978
91              Shimon Peres       Peace  1994
109          Wilhelm Ostwald   Chemistry  1909
121               Aaron Klug   Chemistry  1982
131               Aaron Klug   Chemistry  1982
...                      ...         ...   ...
1039  Aleksandr M. Prokhorov     Physics  1964
1040           Patrick White  Literature  1973
1042           John Harsanyi   Economics  1994
1047        Brian P. Schmidt     Physics  2011
1050    Luis Federico Leloir   Chemistry  1970

[147 rows x 3 columns]

In [218]:
df = df.reindex(np.random.permutation(df.index))
df = df.drop_duplicates(['name', 'category', 'year'])
df = df.sort_index()
df.count()

name              900
category          901
country           818
date_of_birth     892
date_of_death     590
gender            893
link              900
place_of_birth    866
place_of_death    548
text              900
year              900
dtype: int64

In [155]:
df[df['name'].isin(df[df.duplicated('name')]['name'])].sort_values(['name'], ascending = [1])
#Andrew Schally
#Ragnar Granit
#Sidney Altman
#Robert Bárány

,name,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
104,Andrew Schally,NaN,NaN,"November 30, 1926",NaN,male,http://en.wikipedia.org/wiki/Andrew_Schally,"Vilnius , Second Polish Republic",NaN,"Andrew Schally *, born in then Poland, now Li...",1977
712,Andrew Schally,NaN,NaN,"November 30, 1926",NaN,male,http://en.wikipedia.org/wiki/Andrew_Schally,"Vilnius , Second Polish Republic",NaN,"Andrew Schally *, born in Wilno, Second Polis...",1976
548,Frederick Sanger,Chemistry,United Kingdom,1918-08-13,2013-11-19,male,http://en.wikipedia.org/wiki/Frederick_Sanger,"Rendcomb, Gloucestershire, England","Cambridge, England","Frederick Sanger , Chemistry, 1958",1958
580,Frederick Sanger,Chemistry,United Kingdom,1918-08-13,2013-11-19,male,http://en.wikipedia.org/wiki/Frederick_Sanger,"Rendcomb, Gloucestershire, England","Cambridge, England","Frederick Sanger , Chemistry, 1980",1980
292,John Bardeen,Physics,United States,1908-05-23,1991-01-30,male,http://en.wikipedia.org/wiki/John_Bardeen,"Madison, Wisconsin , U.S.","Boston, Massachusetts , U.S.","John Bardeen , Physics, 1956",1956
326,John Bardeen,Physics,United States,1908-05-23,1991-01-30,male,http://en.wikipedia.org/wiki/John_Bardeen,"Madison, Wisconsin , U.S.","Boston, Massachusetts , U.S.","John Bardeen , Physics, 1972",1972
285,Linus C. Pauling,Chemistry,United States,"February 28, 1901","August 19, 1994",male,http://en.wikipedia.org/wiki/Linus_Pauling,"Portland, Oregon","Big Sur, California","Linus C. Pauling , Chemistry, 1954",1954
309,Linus C. Pauling,Peace,United States,"February 28, 1901","August 19, 1994",male,http://en.wikipedia.org/wiki/Linus_Pauling,"Portland, Oregon","Big Sur, California","Linus C. Pauling , Peace, 1962",1962
919,Marie Curie,Chemistry,France,7 November 1867,4 July 1934,female,http://en.wikipedia.org/wiki/Marie_Curie,"Warsaw , Poland","Sancellemoz , France","Marie Curie , born in then Russian Empire, no...",1911
910,Marie Curie,Physics,France,7 November 1867,4 July 1934,female,http://en.wikipedia.org/wiki/Marie_Curie,"Warsaw , Poland","Sancellemoz , France","Marie Curie , born in then Russian Empire, no...",1903
706,Marie Skłodowska-Curie,Physics,Poland,7 November 1867,4 July 1934,female,http://en.wikipedia.org/wiki/Marie_Curie,"Warsaw , Poland","Sancellemoz , France","Marie Skłodowska-Curie , born in partitioned ...",1903
709,Marie Skłodowska-Curie,Chemistry,Poland,7 November 1867,4 July 1934,female,http://en.wikipedia.org/wiki/Marie_Curie,"Warsaw , Poland","Sancellemoz , France","Marie Skłodowska-Curie , born in partitioned ...",1911
960,Ragnar Granit,Physiology or Medicine,Finland,"October 30, 1900","March 12, 1991",None,http://en.wikipedia.org/wiki/Ragnar_Granit,"Helsinki , Finland","Stockholm , Sweden","Ragnar Granit , born in the Grand Duchy of Fi...",1809
650,Ragnar Granit,Physiology or Medicine,Sweden,"October 30, 1900","March 12, 1991",None,http://en.wikipedia.org/wiki/Ragnar_Granit,"Helsinki , Finland","Stockholm , Sweden","Ragnar Granit , born in then Russian Empire, ...",1967
820,Robert Bárány,NaN,NaN,22 April 1876,8 April 1936,male,http://en.wikipedia.org/wiki/Robert_B%C3%A1r%C...,"Vienna , Austria-Hungary","Uppsala , Sweden","Robert Bárány *, born in then Austria-Hungary...",1914
1016,Robert Bárány,Physiology or Medicine,Austria,22 April 1876,8 April 1936,male,http://en.wikipedia.org/wiki/Robert_B%C3%A1r%C...,"Vienna , Austria-Hungary","Uppsala , Sweden","Robert Bárány , Physiology or Medicine, 1914",1914
995,Sidney Altman,Chemistry,Canada,"May 7, 1939",NaN,male,http://en.wikipedia.org/wiki/Sidney_Altman,"Montreal, Quebec , Canada",NaN,"Sidney Altman , Chemistry, 1989",1989
396,Sidney Altman,Chemistry,United States,"May 7, 1939",NaN,male,http://en.wikipedia.org/wiki/Sidney_Altman,"Montreal, Quebec , Canada",NaN,"Sidney Altman , born in Canada , Chemistry, 1990",1990

In [156]:
df[df['name'].isin(['Andrew Schally','Ragnar Granit','Sidney Altman','Robert Bárány'])]

,name,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
104,Andrew Schally,NaN,NaN,"November 30, 1926",NaN,male,http://en.wikipedia.org/wiki/Andrew_Schally,"Vilnius , Second Polish Republic",NaN,"Andrew Schally *, born in then Poland, now Li...",1977
396,Sidney Altman,Chemistry,United States,"May 7, 1939",NaN,male,http://en.wikipedia.org/wiki/Sidney_Altman,"Montreal, Quebec , Canada",NaN,"Sidney Altman , born in Canada , Chemistry, 1990",1990
650,Ragnar Granit,Physiology or Medicine,Sweden,"October 30, 1900","March 12, 1991",None,http://en.wikipedia.org/wiki/Ragnar_Granit,"Helsinki , Finland","Stockholm , Sweden","Ragnar Granit , born in then Russian Empire, ...",1967
712,Andrew Schally,NaN,NaN,"November 30, 1926",NaN,male,http://en.wikipedia.org/wiki/Andrew_Schally,"Vilnius , Second Polish Republic",NaN,"Andrew Schally *, born in Wilno, Second Polis...",1976
820,Robert Bárány,NaN,NaN,22 April 1876,8 April 1936,male,http://en.wikipedia.org/wiki/Robert_B%C3%A1r%C...,"Vienna , Austria-Hungary","Uppsala , Sweden","Robert Bárány *, born in then Austria-Hungary...",1914
960,Ragnar Granit,Physiology or Medicine,Finland,"October 30, 1900","March 12, 1991",None,http://en.wikipedia.org/wiki/Ragnar_Granit,"Helsinki , Finland","Stockholm , Sweden","Ragnar Granit , born in the Grand Duchy of Fi...",1809
995,Sidney Altman,Chemistry,Canada,"May 7, 1939",NaN,male,http://en.wikipedia.org/wiki/Sidney_Altman,"Montreal, Quebec , Canada",NaN,"Sidney Altman , Chemistry, 1989",1989
1016,Robert Bárány,Physiology or Medicine,Austria,22 April 1876,8 April 1936,male,http://en.wikipedia.org/wiki/Robert_B%C3%A1r%C...,"Vienna , Austria-Hungary","Uppsala , Sweden","Robert Bárány , Physiology or Medicine, 1914",1914

In [164]:
df[df['name'] == 'Marie Skłodowska-Curie']

Empty DataFrame
Columns: [name, category, country, date_of_birth, date_of_death, gender, link, place_of_birth, place_of_death, text, year]
Index: []

In [162]:
df[df['name'] == 'Marie Skłodowska-Curie']
# df = df.set_index('name')
# df.loc['Marie Skłodowska-Curie', 'name']
# df = df.reset_index()
df.loc[706, 'name'] = 'Marie Curie'
df.loc[709, 'name'] = 'Marie Curie'
df[df['name'] == 'Marie Skłodowska-Curie']

Empty DataFrame
Columns: [name, category, country, date_of_birth, date_of_death, gender, link, place_of_birth, place_of_death, text, year]
Index: []

In [172]:
df.loc[820, 'category'] = 'Physiology or Medicine'
df.loc[369, 'year'] = 1989
df.loc[960, 'year'] = 1967
df.loc[712, 'year'] = 1977
df.loc[104, 'category'] = 'Physiology or Medicine'
df.loc[712, 'category'] = 'Physiology or Medicine'
df[df['name'].isin(['Andrew Schally','Ragnar Granit','Sidney Altman','Robert Bárány'])]
#list(df.index[df['name'] == 'Andrew Schally']) # index = 712

,name,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
396,Sidney Altman,Chemistry,United States,"May 7, 1939",NaN,male,http://en.wikipedia.org/wiki/Sidney_Altman,"Montreal, Quebec , Canada",NaN,"Sidney Altman , born in Canada , Chemistry, 1990",1990.0
712,Andrew Schally,Physiology or Medicine,NaN,"November 30, 1926",NaN,male,http://en.wikipedia.org/wiki/Andrew_Schally,"Vilnius , Second Polish Republic",NaN,"Andrew Schally *, born in Wilno, Second Polis...",1977.0
820,Robert Bárány,Physiology or Medicine,NaN,22 April 1876,8 April 1936,male,http://en.wikipedia.org/wiki/Robert_B%C3%A1r%C...,"Vienna , Austria-Hungary","Uppsala , Sweden","Robert Bárány *, born in then Austria-Hungary...",1914.0
960,Ragnar Granit,Physiology or Medicine,Finland,"October 30, 1900","March 12, 1991",None,http://en.wikipedia.org/wiki/Ragnar_Granit,"Helsinki , Finland","Stockholm , Sweden","Ragnar Granit , born in the Grand Duchy of Fi...",1967.0
995,Sidney Altman,Chemistry,Canada,"May 7, 1939",NaN,male,http://en.wikipedia.org/wiki/Sidney_Altman,"Montreal, Quebec , Canada",NaN,"Sidney Altman , Chemistry, 1989",1989.0

In [203]:
list(df.index[df['name'] == 'Andrew Schally'])

[712]

In [206]:
df[df['gender'] == 'None']

Empty DataFrame
Columns: [name, category, country, date_of_birth, date_of_death, gender, link, place_of_birth, place_of_death, text, year]
Index: []

In [210]:
df.loc[650, 'gender'] = 'male'
df.loc[960, 'gender'] = 'male'
df[df.gender.isna()]

,name,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
3,Institut de Droit International,Peace,Belgium,None,None,None,http://en.wikipedia.org/wiki/Institut_de_Droit...,None,None,"Institut de Droit International , Peace, 1904",1904.0
156,Friends Service Council,Peace,United Kingdom,None,None,None,http://en.wikipedia.org/wiki/Friends_Service_C...,None,None,"Friends Service Council , Peace, 1947",1947.0
267,American Friends Service Committee (The Quakers),Peace,United States,None,None,None,http://en.wikipedia.org/wiki/American_Friends_...,None,None,American Friends Service Committee (The Quake...,1947.0
574,Amnesty International,Peace,United Kingdom,None,None,None,http://en.wikipedia.org/wiki/Amnesty_Internati...,None,None,"Amnesty International , Peace, 1977",1977.0
696,Konstantin Novoselov,Physics,NaN,23 August 1974,NaN,None,http://en.wikipedia.org/wiki/Konstantin_Novoselov,"Nizhny Tagil , Russian SFSR , Soviet Union",NaN,"Konstantin Novoselov *, Physics, 2010",2010.0
947,Médecins Sans Frontières,Peace,France,None,None,None,http://en.wikipedia.org/wiki/M%C3%A9decins_San...,None,None,"Médecins Sans Frontières , Peace, 1999",1999.0
1000,Pugwash Conferences on Science and World Affairs,Peace,Canada,None,None,None,http://en.wikipedia.org/wiki/Pugwash_Conferenc...,None,None,Pugwash Conferences on Science and World Affai...,1995.0
1033,International Atomic Energy Agency,Peace,Austria,None,None,None,http://en.wikipedia.org/wiki/International_Ato...,None,None,"International Atomic Energy Agency , Peace, 2005",2005.0
104,NaN,Physiology or Medicine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [213]:
df[df['category'].isna()]
df.loc[812,'category'] = 'Physiology or Medicine'
df.loc[815,'category'] = 'Economics'
df.loc[922,'category'] = 'Physiology or Medicine'
df[df['category'].isna()]
df.loc[958,'year'] = 1939
df.loc[959,'year'] = 1945
df[df.year == 1809]

Empty DataFrame
Columns: [name, category, country, date_of_birth, date_of_death, gender, link, place_of_birth, place_of_death, text, year]
Index: []

In [220]:
df['date_of_birth'] = pd.to_datetime(df['date_of_birth'], errors = 'raise')
df['date_of_birth']

0      1927-10-08
1      1892-10-09
3             NaT
4      1829-07-26
5      1862-08-29
          ...
1045   1951-09-30
1046   1948-11-26
1048   1878-11-01
1049   1887-04-10
1051   1931-11-26
Name: date_of_birth, Length: 902, dtype: datetime64[ns]

In [240]:
pd.to_datetime(df['date_of_death'], errors = 'raise')
# df[df['date_of_death'] == '1968-23-07']
# list(df.index[df['date_of_death'] == '1968-23-07'])
# df.loc[list(df.index[df['date_of_death'] == '1968-23-07']), 'date_of_death'] = '1968-07-23'
# df.loc[list(df.index[df['date_of_death'] == 'May 30, 2011 (aged 89)']), 'date_of_death'] = 'May 30, 2011'
# df.loc[list(df.index[df['date_of_death'] == 'np.nan']), 'date_of_death'] = np.nan
# df.loc[list(df.index[df['date_of_death'] == 'Diederik Korteweg']), 'date_of_death'] = '1923-03-08'
# df.loc[list(df.index[df['date_of_death'] == '1 February 1976, age 74']), 'date_of_death'] = '1976-02-01'

0      2002-03-24
1      1975-03-13
3             NaT
4      1912-10-06
5      1949-05-06
          ...
1045          NaT
1046          NaT
1048   1959-05-05
1049   1971-09-21
1051          NaT
Name: date_of_death, Length: 902, dtype: datetime64[ns]

In [241]:
df.iloc[[5,815],[1,2]]

      category  country
6        Peace  Belgium
935  Chemistry      NaN